Add `_as_tensor_variable` converter for pandas objects
pymc-devs/pymc3 pull request #5920
Opened 2022-06-22 15:19 UTC by juanitorduz

This is an attempt to solve https://github.com/pymc-devs/pymc/issues/5877

@ricardoV94 I went through `pymc/aesaraf.py` but I could not figure out by myself where to add your suggestion. I decided to open a PR anyway but I would appreciate some hints on which function this has to be included and tested 🙏

2022-06-22 18:44 UTC, michaelosthege commented
ArviZ has a dependency on pandas already, so you can import it right away:

https://github.com/pymc-devs/pymc/pull/5895

I'd still add it to the requirements and conda envs though.

A good placement for this function might be close to the top of the file, because there's already a function for converting observed data, which is slightly similar.

Any idea what to do with multi-indexed DataFrames?

2022-06-22 19:27 UTC, ricardoV94 commented
Oh, we removed pandas dependency on purpose but we didn't check any of our dependencies required it... That's a shame :/

2022-06-24 13:08 UTC, juanitorduz commented
I think this first iteration is ready for review :)

2022-06-24 22:04 UTC, michaelosthege commented on pymc/aesaraf.py
> +        return at.as_tensor_variable(df.to_numpy(), *args, **kwargs)
Let's add `pandas` in the dependencies and be done with it.
It's extremely unlikely that all of PyMC's dependencies will become independent of `pandas`, so we can just keep things simple.

In the unlikely event that all dependencies become `pandas`-independent one can still change this.

2022-06-24 22:04 UTC, michaelosthege commented on pymc/aesaraf.py
> +        return at.as_tensor_variable(df.to_numpy(), *args, **kwargs)
Should we also support `pd.Series`?

2022-06-28 08:55 UTC, juanitorduz commented on pymc/aesaraf.py
> +        return at.as_tensor_variable(df.to_numpy(), *args, **kwargs)
I removed the `if pandas` block and added support for pandas Series (and tests) in https://github.com/pymc-devs/pymc/pull/5920/commits/3c3e74b4b2db0ff84ceab6372cd627f1ee59ab3b

2022-06-28 08:55 UTC, juanitorduz commented on pymc/aesaraf.py
> +        return at.as_tensor_variable(df.to_numpy(), *args, **kwargs)
Is it necessary to add explicitly the pandas dependency in the conda envs explicitly as part of this PR?

2022-06-28 09:00 UTC, juanitorduz commented
Any tips on why the `codecov/project` step fails? I am adding tests  ¯\\_(ツ)_/¯

2022-06-28 09:36 UTC, michaelosthege commented on pymc/aesaraf.py
> +        return at.as_tensor_variable(df.to_numpy(), *args, **kwargs)
> Is it necessary to add explicitly the pandas dependency in the conda envs explicitly as part of this PR?

Yes, please add it in the conda-envs and requirements.txt

2022-06-29 13:25 UTC, juanitorduz commented on pymc/aesaraf.py
> +        return at.as_tensor_variable(df.to_numpy(), *args, **kwargs)
In https://github.com/pymc-devs/pymc/pull/5920/commits/068b803aed64d0044a24fdc57d9f27a1505eae25 I added pandas to the `requirements.txt`, whic seems the only place it was missing. All the `conda-envs` have it as well as `requirements-dev.txt` .

2022-06-29 13:32 UTC, michaelosthege approved these changes
Looks good to me, but I'll ask in the chat for a second person to look at it & merge (assuming the pipeline goes green).

2022-06-29 13:39 UTC, twiecki approved these changes

2022-06-29 16:24 UTC, ricardoV94 requested changes

2022-06-29 16:24 UTC, ricardoV94 commented on requirements.txt
> +pandas>=0.24.0
You will have to add the dependency in the conda environments as well. Does this version number have a specific meaning/reason?

2022-06-29 16:24 UTC, ricardoV94 commented on pymc/tests/test_aesaraf.py
> +    pd = pytest.importorskip("pandas")
If pandas is an explicit dependency we don't need the importorskip (also in the other tests)

2022-06-29 17:28 UTC, michaelosthege commented on requirements.txt
> +pandas>=0.24.0
The same entry is already in the conda environments on `main`

2022-06-29 17:30 UTC, ricardoV94 commented on requirements.txt
> +pandas>=0.24.0
Oh I didn't expect that

2022-06-30 07:28 UTC, juanitorduz commented on pymc/tests/test_aesaraf.py
> +    pd = pytest.importorskip("pandas")
removed them in https://github.com/pymc-devs/pymc/pull/5920/commits/67d72a486f0144e44dd59bb4a17fb5e99541f41f

2022-06-30 13:03 UTC, michaelosthege requested changes

2022-06-30 13:03 UTC, michaelosthege commented on pymc/tests/test_aesaraf.py
> +    df: pd.DataFrame = pd.Series(np_array)
```suggestion
    df = pd.Series(np_array)
```
```suggestion
    df: pd.DataFrame = pd.Series(np_array)
```

2022-06-30 13:03 UTC, michaelosthege commented on pymc/tests/test_aesaraf.py
> +    df: pd.DataFrame = pd.DataFrame(np_array)
```suggestion
    df = pd.DataFrame(np_array)
```

2022-06-30 13:46 UTC, juanitorduz commented on pymc/tests/test_aesaraf.py
> +    df: pd.DataFrame = pd.DataFrame(np_array)
thank you!

2022-06-30 17:15 UTC, michaelosthege approved these changes

2022-06-30 17:17 UTC, michaelosthege commented
The changes requested by @ricardoV94 were made.
I'll merge now.

Thanks for this contribution @juanitorduz !

2022-06-30 17:18 UTC, merged