Allow access to different nutpie backends via pip-style syntax
pymc-devs/pymc3 pull request #7498
Opened 2024-09-10 10:33 UTC by jessegrabowski

## Description

Adds a pip-style syntax to the `nuts_sampler` argument that allows access to alternative compile backends, when relevant. This lets you get the nutpie jax backend by setting `nuts_sampler='nutpie[jax]'`. For backwards compatibility, `nuts_sampler='nutpie'` is equivalent to `nuts_sampler='nutpie[numba]'`.

The current PR only deals with nutpie, but we could easily extend this to include the default PyMC sampler, to compile to JAX, numba, or pytorch directly, without going through nutpie. I'm willing to do that extension in this PR if it is deemed worthwhile..

## Related Issue

- [x] Closes #7497 
- [ ] Related to #

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [x] Included tests that prove the fix is effective or that the new feature works
- [x] Added necessary documentation (docstrings and/or example notebooks)
- [x] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [x] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc--7498.org.readthedocs.build/en/7498/

2024-09-10 10:34 UTC, jessegrabowski commented
I created some global variables to track available backends in `nutpie`, anticipating that we will eventually expand the list to include pytorch. It would be nice if these globals were defined in the nutpie library itself and we just imported them here.

2024-09-10 11:06 UTC, ricardoV94 commented
> The current PR only deals with nutpie, but we could easily extend this to include the default PyMC sampler, to compile to JAX, numba, or pytorch directly

I'm not sure how the other backends (specially JAX) behave with multiprocessing tbh :O Otherwise the idea sounds cool. Perhaps @aseyboldt can weigh in as he has a better picture of how we handle multiprocessing in pm.sample

2024-09-10 11:21 UTC, jessegrabowski commented
Should we go work on a `pmap` for pytensor?

2024-09-10 11:41 UTC, ricardoV94 commented
> Should we go work on a `pmap` for pytensor?

The PyMC codebase would still need to know about it and work around differently for JAX

2024-09-10 11:56 UTC, ricardoV94 commented
With numba backend we could actually do it with threads (with nogil)? Maybe worth opening an issue to investigate different backends for pymc samplers.

Also this shouldn't have to be nuts specific so for that a `backend` argument may make more sense. Something like this was also raised for VI recently IIRC

2024-09-10 11:59 UTC, jessegrabowski commented
Should probably just be `compile_kwargs` like every other pymc function, but I liked my cute syntax.

2024-09-10 12:02 UTC, ricardoV94 commented
> Should probably just be `compile_kwargs` like every other pymc function, but I liked my cute syntax.

Not if we need to change how the samplers are orchestrated

2024-09-10 12:03 UTC, ricardoV94 commented
But compile kwargs already works anyway

2024-09-10 12:09 UTC, jessegrabowski commented
> But compile kwargs already works anyway

What do you mean, `pm.sample` already takes `compile_kwargs`? It's undocumented if so.

2024-09-10 12:10 UTC, ricardoV94 commented
> > But compile kwargs already works anyway
> 
> What do you mean, `pm.sample` already takes `compile_kwargs`? It's undocumented if so.

It doesn't? Maybe I've played with global mode then

2024-09-12 10:34 UTC, lucianopaz requested changes
@jessegrabowski, this looks very nice. I left a few suggestions though

2024-09-12 10:34 UTC, lucianopaz commented on pymc/sampling/mcmc.py
> +                return NUTPIE_DEFAULT_BACKEND
You could also get a `None` match if the string is misformatted. For example, `nutpie[jax` would return a `None` match. I suggest that you test exact equality to set the default option, and if you get `None` then raise a `ValueError`.
```suggestion
            if string == "nutpie":
                return NUTPIE_DEFAULT_BACKEND
            elif match is None:
                raise ValueError(f"Could not parse nutpie backend. Found {string!r}")
```

2024-09-12 10:34 UTC, lucianopaz commented on pymc/sampling/mcmc.py
> +                raise ValueError(f'Expected one of {expected}; found "{result}"')
```suggestion
                raise ValueError(
                    'Could not parse nutpie backend. Expected one of {expected}; found "{result}"'
                )
```

2024-09-12 10:34 UTC, lucianopaz commented on tests/sampling/test_mcmc_external.py
> +@pytest.mark.parametrize("nuts_sampler", ["pymc", "nutpie", "blackjax", "numpyro"])
```suggestion
@pytest.mark.parametrize(
    "nuts_sampler",
    ["pymc", "nutpie", "nutpie[jax]", "blackjax", "numpyro"],
)
```

2024-09-12 10:34 UTC, lucianopaz commented on tests/sampling/test_mcmc_external.py
> +    with pytest.raises(ValueError, match='Expected one of "numba" or "jax"; found "invalid"'):
```suggestion
    with pytest.raises(
        ValueError,
        match='Could not parse nutpie backend. Expected one of "numba" or "jax"; found "invalid"',
    ):
```

2024-09-12 10:34 UTC, lucianopaz commented on tests/sampling/test_mcmc_external.py
> +
```suggestion

    with pytest.raises(ValueError, match="Could not parse nutpie backend. Found 'nutpie[bad'"):
        with pymc_model:
            sample(nuts_sampler="nutpie[bad", random_seed=123, chains=2, tune=500, draws=500)
```

2024-09-14 15:47 UTC, twiecki commented
I posted this PR with comments into GPT o1-mini:
<details>
---

#### **Summary**

This pull request introduces a pip-style syntax for specifying different Nutpie backends within the `nuts_sampler` argument of PyMC's `pm.sample` function. Users can now select a specific backend by using a syntax like `nuts_sampler='nutpie[jax]'`, with `nuts_sampler='nutpie'` defaulting to `nuts_sampler='nutpie[numba]'` for backward compatibility. This enhancement aims to provide greater flexibility and performance optimization by allowing users to choose the most suitable backend for their computational needs.

**Key Changes:**

1. **Code Enhancements:**
   - **Backend Parsing:** Introduces a helper function `_extract_backend` to parse and extract backend specifications from the `nuts_sampler` string.
   - **Type Definitions:** Defines new type aliases for better type safety and clarity.
   - **Sampler Integration:** Updates sampling functions to handle the new backend specifications seamlessly.
   - **Error Handling:** Improves error messages to provide clearer guidance when invalid backend specifications are provided.

2. **Testing Improvements:**
   - **Expanded Test Coverage:** Adds new test cases to cover various backend specifications, including valid and invalid scenarios.
   - **Refactored Tests:** Utilizes fixtures and helper functions to reduce redundancy and enhance test maintainability.

3. **Documentation Updates:**
   - **Docstrings:** Enhances existing docstrings to reflect the new backend syntax and usage examples.
   - **ReadTheDocs:** Provides a preview link to the updated documentation for further review.

4. **GitHub Discussions:**
   - **Collaborative Feedback:** Addresses feedback from reviewers, refining error handling and test cases based on suggestions.
   - **Future Considerations:** Mentions potential future expansions, such as supporting additional backends like PyTorch.

---

#### **Detailed Review**

##### **1. Code Changes**

**a. `pymc/sampling/mcmc.py`**

- **Type Aliases:**
  ```python
  ExternalNutsSampler = Literal["nutpie", "numpyro", "blackjax"]
  NutsSampler = Literal["pymc"] | ExternalNutsSampler
  NutpieBackend = Literal["numba", "jax"]
  ```
  - **Purpose:** Enhances type safety by clearly defining allowed values for samplers and Nutpie backends.
  - **Suggestion:** Consider placing these type aliases in a separate module if they are to be reused across different parts of the codebase.

- **Global Variables:**
  ```python
  NUTPIE_BACKENDS = get_args(NutpieBackend)
  NUTPIE_DEFAULT_BACKEND = cast(NutpieBackend, "numba")
  ```
  - **Purpose:** Manages available backends and sets the default backend to `numba`.
  - **Suggestion:** If the list of backends is expected to grow, consider loading them dynamically or configuring them via external settings.

- **Backend Extraction Function:**
  ```python
  def extract_backend(string: str) -> NutpieBackend:
      match = re.search(r"(?<=\[)[^\]]+(?=\])", string)
      if match is None:
          return NUTPIE_DEFAULT_BACKEND
      result = cast(NutpieBackend, match.group(0))
      if result not in NUTPIE_BACKENDS:
          last_option = f"{NUTPIE_BACKENDS[-1]}"
          expected = (
              ", ".join([f'"{x}"' for x in NUTPIE_BACKENDS[:-1]]) + f' or "{last_option}"'
          )
          raise ValueError(f'Expected one of {expected}; found "{result}"')
      return result
  ```
  - **Purpose:** Parses the backend from the `nuts_sampler` string and validates it.
  - **Strengths:** 
    - Uses regex to extract backend specifications.
    - Provides clear error messages when invalid backends are specified.
  - **Suggestions:**
    - **Regex Robustness:** Ensure the regex accurately captures backends in all valid formats and handles edge cases (e.g., multiple brackets, unexpected characters).
    - **Error Messaging:** The error message could be more descriptive by including the entire input string to aid debugging.

- **Sampler Integration:**
  ```python
  if sampler.startswith("nutpie"):
      backend = extract_backend(sampler)
      compiled_model = nutpie.compile_pymc_model(model, backend=backend)
  ```
  - **Purpose:** Integrates the backend specification into the Nutpie sampler.
  - **Suggestions:**
    - **Namespace Consistency:** Ensure that all references to samplers and backends maintain consistent naming conventions.
    - **Extensibility:** If future backends are added, verify that the integration logic remains scalable.

**b. `pymc/sampling/jax.py`**

- **Type Alias Update:**
  ```python
  JaxNutsSampler = Literal["numpyro", "blackjax"]
  ```
  - **Purpose:** Defines allowed JAX-based samplers.
  - **Suggestion:** Similar to `ExternalNutsSampler`, consider centralizing type aliases for better maintainability.

- **Function Signature Update:**
  ```python
  def sample_jax_nuts(
      ...
      nuts_sampler: JaxNutsSampler,
      ...
  ) -> az.InferenceData:
  ```
  - **Purpose:** Enforces that only `numpyro` and `blackjax` are accepted as JAX-based samplers.
  - **Suggestion:** Ensure that all downstream functions and users are aware of this restriction to prevent runtime errors.

**c. `tests/sampling/test_mcmc_external.py`**

- **Test Refactoring:**
  ```python
  @pytest.fixture
  def pymc_model():
      with Model() as m:
          x = Normal("x", 100, 5)
          y = Data("y", [1, 2, 3, 4])
          Data("z", [100, 190, 310, 405])
  
          Normal("L", mu=x, sigma=0.1, observed=y)
  
      return m
  ```
  - **Purpose:** Defines a reusable model fixture for tests.
  - **Strengths:** Promotes DRY (Don't Repeat Yourself) principles by avoiding redundancy in test definitions.

- **New Test Cases:**
  - **Backend Options Test:**
    ```python
    @pytest.mark.parametrize("backend", ["numba", "jax"], ids=["numba", "jax"])
    def test_numba_backend_options(pymc_model, recwarn, backend):
        ...
    ```
    - **Purpose:** Validates that specifying different Nutpie backends works as expected.
  
  - **Invalid Backend Test:**
    ```python
    def test_invalid_nutpie_backend_raises(pymc_model):
        pytest.importorskip("nutpie")
        with pytest.raises(ValueError, match='Could not parse nutpie backend. Expected one of "numba" or "jax"; found "invalid"'):
            with pymc_model:
                sample(nuts_sampler="nutpie[invalid]", ...)
    ```
    - **Purpose:** Ensures that invalid backend specifications raise appropriate errors.
    - **Strengths:** Provides clear assertions that verify error handling mechanisms.

- **Test Helper Function:**
  ```python
  def check_external_sampler_output(warns, idata1, idata2, sample_kwargs):
      ...
  ```
  - **Purpose:** Abstracts common test assertions to enhance readability and maintainability.
  - **Suggestion:** Ensure that this function covers all necessary assertions to comprehensively validate sampler outputs.

**d. Documentation Updates**

- **Docstring Enhancements:**
  ```python
  nuts_sampler : str, default "pymc"
      Which NUTS implementation to run. One of ["pymc", "nutpie", "blackjax", "numpyro"]. In addition, the compilation
      backend for the chosen sampler can be set using square brackets, if available. For example, "nutpie[jax]" will
      use the JAX backend for the nutpie sampler. Currently, "nutpie[jax]" and "nutpie[numba]" are allowed.
  ```
  - **Purpose:** Clarifies the usage of the `nuts_sampler` argument with examples.
  - **Strengths:** Provides users with clear guidance on how to specify different backends.

- **Documentation Preview:**
  - **Link:** [ReadTheDocs Preview](https://pymc--7498.org.readthedocs.build/en/7498/)
  - **Suggestion:** Verify that all new features are accurately reflected in the documentation, including edge cases and error scenarios.

---

##### **2. Testing Enhancements**

- **Increased Coverage:**
  - **Codecov Report:** Indicates a patch coverage of 47.83% with 12 lines missing.
  - **Action Required:** Ensure that all new code paths, especially those in [...]

2024-10-15 11:02 UTC, jessegrabowski commented
Close this as stale now that #7535 is merged? Or is there interest in this syntax still.

2024-10-15 11:13 UTC, ricardoV94 commented
I think this syntax is a bit more ergonomic

2024-10-16 08:32 UTC, aseyboldt commented
I like the syntax :-)
But maybe we should go with jax by default? I know it is a change, but I think right now this is much more robust.

2024-10-16 08:35 UTC, jessegrabowski commented
Thoughts on the best way to ask for the gradient backend in this syntax? Or `nutpie[jax]` should just always set both, and consider the mixed case to be "advanced"?

2024-10-16 08:54 UTC, ricardoV94 commented
> I like the syntax :-) But maybe we should go with jax by default? I know it is a change, but I think right now this is much more robust.

That will break people's existing code if they don't have jax installed

2024-10-30 15:58 UTC, AlexAndorra commented
This looks super helpful @jessegrabowski !!

2025-11-12 08:16 UTC, ricardoV94 commented
I know there was some back and forth here but I think the `backend=mode` kwarg would be nicer. So you can do `pm.sample(backend="numba")` as well as `pm.sample(nuts_sampler="nutpie", backend="numba")`, and `pm.sample_posterior_predictive(backend="numba")`

That is, the backend is somewhat orthogonal to the sampler, be it pymc or not?

Basically a less verbose shortcut for the most common use of `compile_kwargs` (which can still exist for more fine tweaks)

2025-11-12 13:46 UTC, jessegrabowski commented
Yeah I think I agree. I've cooled on all the clever string stuff recently. I think I'll close this PR and open a fresh one with the backend argument.

2025-11-12 13:46 UTC, closed without merging